--BASE
SELECT
  S.CIUDAD_SUCURSAL,
  COUNT(*),
  SUM(C.SALDO)
FROM 
  CUENTA C INNER JOIN SUCURSAL S ON S.NOMBRE_SUCURSAL = C.NOMBRE_SUCURSAL
GROUP BY
  S.CIUDAD_SUCURSAL;

--FUNCION DE SUMAR
CREATE OR REPLACE FUNCTION FM_GET_SUM_SALDO_CUENTA 
(
  P_CIUDAD IN VARCHAR2 
) RETURN NUMBER AS 
TOTAL NUMBER;
BEGIN
  SELECT
    SUM(C.SALDO) AS TOTAL_SUM
  INTO
    TOTAL
  FROM 
    CUENTA C INNER JOIN SUCURSAL S ON S.NOMBRE_SUCURSAL = C.NOMBRE_SUCURSAL
  WHERE
    S.CIUDAD_SUCURSAL = P_CIUDAD;
  RETURN TOTAL;
END FM_GET_SUM_SALDO_CUENTA;

--FUNCION DE CONTAR
CREATE OR REPLACE FUNCTION FM_COUNT_CUENTA 
(
  P_CIUDAD IN VARCHAR2 
) RETURN NUMBER AS 
CONTADOS NUMBER;
BEGIN
  SELECT
    COUNT(*) AS TOTAL_COUNT
  INTO
    CONTADOS
  FROM 
    CUENTA C INNER JOIN SUCURSAL S ON S.NOMBRE_SUCURSAL = C.NOMBRE_SUCURSAL
  WHERE
    S.CIUDAD_SUCURSAL = P_CIUDAD;
  RETURN CONTADOS;
END FM_COUNT_CUENTA;

--PRUEBA AMBAS
SELECT DISTINCT
  S.CIUDAD_SUCURSAL,
  FM_GET_SUM_SALDO_CUENTA(S.CIUDAD_SUCURSAL) AS SUMA_CUENTA,
  FM_COUNT_CUENTA(S.CIUDAD_SUCURSAL) AS CONTEO_CUENTAS
FROM 
  SUCURSAL S;

--FUNCION QUE DEVUELVE EL MAXIMO IMPORTE DE TODOS LOS PRESTAMOS
CREATE OR REPLACE FUNCTION FM_MAX_IMPORTE RETURN NUMBER AS 
max_imp NUMBER;
BEGIN
  SELECT
    MAX(IMPORTE)
  INTO
    max_imp
  FROM
    PRESTAMO;
  RETURN max_imp;
END FM_MAX_IMPORTE;

--PROBANDO LA FUNCION DE MAX PRESTAMO
SELECT
  MAX(IMPORTE)
FROM
  PRESTAMO;
  
--IMPLEMENTANDO CLIENTE CON MAX IMPORTE
SELECT
  C.NOMBRE_CLIENTE,
  C.CALLE_CLIENTE,
  C.CIUDAD_CLIENTE
FROM 
  CLIENTE C INNER JOIN PRESTATARIO PR ON C.NOMBRE_CLIENTE = PR.NOMBRE_CLIENTE
    INNER JOIN PRESTAMO P ON P.NUMERO_PRESTAMO = PR.NUMERO_PRESTAMO
WHERE
  P.IMPORTE = FM_MAX_IMPORTE;