--CREAR TABLA
CREATE TABLE PRUEBA3_21411165(
CODIGO NUMBER(12),
NOMBRE VARCHAR2(50)
);

--FUNCION QUE INCREMENTA
CREATE OR REPLACE FUNCTION FN_AUTONUMERICO_PRUEBA3
(
  P_INCREMENTA IN VARCHAR2 
) RETURN NUMBER AS 
  nMax NUMBER;
BEGIN
  SELECT
    MAX(CODIGO)
  INTO
    nMax
  FROM
    PRUEBA3_21411165;
  RETURN NVL(nMax,0) + P_INCREMENTA;
END FN_AUTONUMERICO_PRUEBA3;

--TRIGGER
CREATE OR REPLACE TRIGGER TR_PRUEBA3_21411165_BI 
BEFORE INSERT ON PRUEBA3_21411165 FOR EACH ROW
BEGIN
  IF(:NEW.CODIGO IS NULL) THEN
    :NEW.CODIGO := FN_AUTONUMERICO_PRUEBA3(1);
  END IF;
END;