--a
CREATE MATERIALIZED VIEW MVW_VENTAS 
NOCACHE 
USING INDEX 
REFRESH ON DEMAND 
COMPLETE 
USING DEFAULT ROLLBACK SEGMENT 
DISABLE QUERY REWRITE AS 
SELECT
  TO_CHAR(FECHA,'YYYY'),
  SUM(CASE CLIENTE WHEN 'Cliente 0' THEN TOTAL ELSE NULL END) AS Cliente_0,
  SUM(CASE CLIENTE WHEN 'Cliente 2' THEN TOTAL ELSE NULL END) AS Cliente_2,
  SUM(CASE CLIENTE WHEN 'Cliente 3' THEN TOTAL ELSE NULL END) AS Cliente_3,
  SUM(TOTAL) AS TOTAL
FROM ventas
WHERE
  CLIENTE IN ('Cliente 0', 'Cliente 2', 'Cliente 3')
GROUP BY
  TO_CHAR(FECHA,'YYYY');


--b
--Creamos la tabla
CREATE TABLE "AHORRO"."MVW_VENTAS_TABLE" 
(	"FECHA" VARCHAR2(4 BYTE), 
"CLIENTE_0" NUMBER, 
"CLIENTE_2" NUMBER, 
"CLIENTE_3" NUMBER, 
"TOTAL" NUMBER
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;

--Creamos el Procedimiento
CREATE OR REPLACE PROCEDURE SP_MVW_VENTAS_UPDATE AS 
BEGIN
  DELETE FROM MVW_VENTAS_TABLE;
  
  INSERT INTO MVW_VENTAS_TABLE
  (SELECT
  TO_CHAR(FECHA,'YYYY'),
  SUM(CASE CLIENTE WHEN 'Cliente 0' THEN TOTAL ELSE NULL END) AS Cliente_0,
  SUM(CASE CLIENTE WHEN 'Cliente 2' THEN TOTAL ELSE NULL END) AS Cliente_2,
  SUM(CASE CLIENTE WHEN 'Cliente 3' THEN TOTAL ELSE NULL END) AS Cliente_3,
  SUM(TOTAL) AS TOTAL
FROM ventas
WHERE
  CLIENTE IN ('Cliente 0', 'Cliente 2', 'Cliente 3')
GROUP BY
  TO_CHAR(FECHA,'YYYY'));
END SP_MVW_VENTAS_UPDATE;

--Ejecutamos Procedimiento
BEGIN
  SP_MVW_VENTAS_UPDATE();
--rollback; 
END;