--objetos de base de datos
--SQL
--indices
--optimizacion diferente a indice
---table spaces
---tablas particionadas
---vistas materializadas

--Crea tablespace para la Data
CREATE TABLESPACE "BANCO_DATA" DATAFILE 
'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\BANCO_DATA.DBF' SIZE 20971520
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;

--Crear Tablespace para los indices
CREATE TABLESPACE "BANCO_INDEX" DATAFILE 
'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\BANCO_INDEX.DBF' SIZE 20971520
LOGGING ONLINE PERMANENT BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;

--Mover las tablas a la nueva Tablespace
ALTER TABLE BANCO.CLIENTE MOVE TABLESPACE BANCO_DATA;
ALTER TABLE BANCO.CUENTA MOVE TABLESPACE BANCO_DATA;
ALTER TABLE BANCO.EMPLEADO MOVE TABLESPACE BANCO_DATA;
ALTER TABLE BANCO.IMPOSITOR MOVE TABLESPACE BANCO_DATA;
ALTER TABLE BANCO.PRESTAMO MOVE TABLESPACE BANCO_DATA;
ALTER TABLE BANCO.PRESTATARIO MOVE TABLESPACE BANCO_DATA;
ALTER TABLE BANCO.SUCURSAL MOVE TABLESPACE BANCO_DATA;
ALTER TABLE BANCO.TRABAJO_A_TIEMPO_COMPLETO MOVE TABLESPACE BANCO_DATA;
ALTER TABLE BANCO.TRABAJO_POR_HORA MOVE TABLESPACE BANCO_DATA;

--Mover los indices a la nueva Tablespace
ALTER INDEX BANCO.CLIENTE_PK REBUILD TABLESPACE BANCO_INDEX;
ALTER INDEX BANCO.CUENTA_PK REBUILD TABLESPACE BANCO_INDEX;
ALTER INDEX BANCO.EMPLEADO_PK REBUILD TABLESPACE BANCO_INDEX;
ALTER INDEX BANCO.IMPOSITOR_PK REBUILD TABLESPACE BANCO_INDEX;
ALTER INDEX BANCO.PRESTAMO_PK REBUILD TABLESPACE BANCO_INDEX;
ALTER INDEX BANCO.PRESTATARIO_PK REBUILD TABLESPACE BANCO_INDEX;
ALTER INDEX BANCO.SUCURSAL_PK REBUILD TABLESPACE BANCO_INDEX;
ALTER INDEX BANCO.TRABAJO_A_TIEMPO_COMPLETO_PK REBUILD TABLESPACE BANCO_INDEX;
ALTER INDEX BANCO.TRABAJO_POR_HORA_PK REBUILD TABLESPACE BANCO_INDEX;
