--------------------------------------------------------
--  DDL for Procedure SP_USUARIOS_CREATE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "AHORRO"."SP_USUARIOS_CREATE" 
(
  P_ID_USUARIO IN USUARIO.ID_USUARIO%TYPE 
, P_CLAVE IN USUARIO.CLAVE%TYPE 
, P_NOMBRE IN USUARIO.NOMBRE%TYPE 
, P_CREADO_POR IN USUARIO.CREADO_POR%TYPE 
, P_MODIFICADO_POR IN USUARIO.MODIFICADO_POR%TYPE 
) AS 
BEGIN
  INSERT INTO USUARIO ( ID_USUARIO,CLAVE, NOMBRE, 
            CREADO_POR, MODIFICADO_POR,FECHA_CREACION)
  VALUES(   P_ID_USUARIO,P_CLAVE, P_NOMBRE, 
            P_CREADO_POR, P_MODIFICADO_POR,SYSDATE);
            
  COMMIT;
END SP_USUARIOS_CREATE;

/
--------------------------------------------------------
--  DDL for Procedure SP_USUARIOS_DELETE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "AHORRO"."SP_USUARIOS_DELETE" 
(
  P_ID_USUARIO IN USUARIO.ID_USUARIO%TYPE  
) AS 
BEGIN
  DELETE FROM USUARIO
  WHERE
    ID_USUARIO = P_ID_USUARIO;
    
  COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure SP_USUARIOS_READ
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "AHORRO"."SP_USUARIOS_READ" ( P_NOMBRE IN USUARIO.NOMBRE%TYPE , cRETURN OUT SYS_REFCURSOR) IS
BEGIN
  OPEN cRETURN FOR
  SELECT ID_USUARIO, CLAVE, NOMBRE, CREADO_POR, MODIFICADO_POR, FECHA_CREACION, FECHA_MODIFICACION 
  FROM USUARIO 
  WHERE NOMBRE LIKE P_NOMBRE;  
END;

/
--------------------------------------------------------
--  DDL for Procedure SP_USUARIOS_UPDATE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "AHORRO"."SP_USUARIOS_UPDATE" 
(
  P_ID_USUARIO IN USUARIO.ID_USUARIO%TYPE 
, P_CLAVE IN USUARIO.CLAVE%TYPE 
, P_NOMBRE IN USUARIO.NOMBRE%TYPE 
, P_MODIFICADO_POR IN USUARIO.MODIFICADO_POR%TYPE 
) AS 
BEGIN
  UPDATE USUARIO SET 
      CLAVE = P_CLAVE, 
      NOMBRE = P_NOMBRE, 
      MODIFICADO_POR = P_MODIFICADO_POR,
      FECHA_MODIFICACION = SYSDATE
  WHERE
    ID_USUARIO = P_ID_USUARIO;
    
  COMMIT;
END SP_USUARIOS_UPDATE;

/


create or replace FUNCTION FN_USUARIOS_READ( P_NOMBRE IN USUARIO.NOMBRE%TYPE) RETURN T_USUARIO PIPELINED AS
BEGIN
  FOR cReg IN  (SELECT 
                  ID_USUARIO, CLAVE, NOMBRE, 
                  CREADO_POR, MODIFICADO_POR, FECHA_CREACION, FECHA_MODIFICACION 
                FROM USUARIO 
                WHERE NOMBRE LIKE P_NOMBRE) LOOP
      PIPE ROW(T_USUARIO_ROW(cReg.ID_USUARIO, cReg.CLAVE, cReg.NOMBRE, cReg.CREADO_POR, cReg.MODIFICADO_POR, cReg.FECHA_CREACION, cReg.FECHA_MODIFICACION ));
  
  END LOOP;

  RETURN;
END;