--RETORNA EL LOS EMPLEADOS Y SU POSICION DE TRABAJO
SELECT
  E.EMPLOYEE_ID,
  E.FIRST_NAME,
  E.LAST_NAME,
  J.JOB_ID,
  J.JOB_TITLE
FROM
  EMPLOYEES E INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID;
    
--EMPLEADOS CONTRATADOS EL MISMO ANIO QUE SU JEFE
SELECT
  E.EMPLOYEE_ID,
  E.FIRST_NAME,
  E.LAST_NAME,
  E.HIRE_DATE,
  J.EMPLOYEE_ID,
  J.FIRST_NAME,
  J.LAST_NAME,
  J.HIRE_DATE
FROM
  EMPLOYEES E INNER JOIN EMPLOYEES J
    ON E.MANAGER_ID = J.EMPLOYEE_ID AND TO_CHAR(E.HIRE_DATE,'YYYY') = TO_CHAR(J.HIRE_DATE,'YYYY');
    
--EMPLEADOS QUE TRABAJAN EN LA CIUDAD DE SEATLE
SELECT
  E.EMPLOYEE_ID,
  E.FIRST_NAME,
  E.LAST_NAME,
  E.SALARY,
  E.HIRE_DATE,
  L.CITY,
  L.STATE_PROVINCE
FROM
  EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    INNER JOIN LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
WHERE
  L.CITY = 'Seattle';

  --JEFE CON PLANILLA MAS ALTA
  --SUMA DEL SUELDO DE SUS EMPLEADOS MAS EL JEFE
SELECT
  J.EMPLOYEE_ID,
  J.FIRST_NAME,
  J.LAST_NAME,
  J.SALARY,
  COUNT (*) + 1 AS SUBORDINADOS,
  SUM(E.SALARY) + J.SALARY AS TOTAL_SUELDOS 
FROM
  EMPLOYEES E INNER JOIN EMPLOYEES J
    ON E.MANAGER_ID = J.EMPLOYEE_ID
GROUP BY
  J.EMPLOYEE_ID,
  J.FIRST_NAME,
  J.LAST_NAME,
  J.SALARY;

  --EMPLEADO CON SALDO MAS ALTO DE ESTADOS UNIDOS
SELECT
  E.EMPLOYEE_ID,
  E.FIRST_NAME,
  E.LAST_NAME,
  E.SALARY,
  E.HIRE_DATE
FROM
  EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    INNER JOIN LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
      INNER JOIN COUNTRIES C ON C.COUNTRY_ID = L.COUNTRY_ID
WHERE
  C.COUNTRY_ID = 'US'
  AND
    E.SALARY = 
    (
      SELECT
        MAX(E.SALARY) AS MAX_SALDO
      FROM
        EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
          INNER JOIN LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
            INNER JOIN COUNTRIES C ON C.COUNTRY_ID = L.COUNTRY_ID
      WHERE
        C.COUNTRY_ID = 'US'
    );

--DEPARTAMENTO CON MAYOR Y MENOR CANTIDAD DE EMPLEADOS
  
--DEPARTAMENTO CON MAYOR CANTIDAD
SELECT 
  D_E.DEPARTMENT_ID,
    D_E.DEPARTMENT_NAME,
    D_E.CANT_EMPLEADOS
FROM
  (SELECT 
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    COUNT(*) AS CANT_EMPLEADOS
  FROM 
    DEPARTMENTS D
      INNER JOIN EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  GROUP BY
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME) D_E
WHERE 
  D_E.CANT_EMPLEADOS =
(SELECT 
  MAX(D_E.CANT_EMPLEADOS)
FROM
  (SELECT 
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    COUNT(*) AS CANT_EMPLEADOS
  FROM 
    DEPARTMENTS D
      INNER JOIN EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  GROUP BY
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    COUNT(*)) D_E);
    
--DEPARTAMENTO CON MENOR CANTIDAD
SELECT 
  D_E.DEPARTMENT_ID,
    D_E.DEPARTMENT_NAME,
    D_E.CANT_EMPLEADOS
FROM
  (SELECT 
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    COUNT(*) AS CANT_EMPLEADOS
  FROM 
    DEPARTMENTS D
      INNER JOIN EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  GROUP BY
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME) D_E
WHERE 
  D_E.CANT_EMPLEADOS =
(SELECT 
  MIN(D_E.CANT_EMPLEADOS)
FROM
  (SELECT 
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    COUNT(*) AS CANT_EMPLEADOS
  FROM 
    DEPARTMENTS D
      INNER JOIN EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  GROUP BY
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    COUNT(*)) D_E);

-- DPTO CON MAYOR Y MENOR
SELECT 
  *
FROM
  (--DEPARTAMENTO CON MENOR CANTIDAD
SELECT 
  D_E.DEPARTMENT_ID,
    D_E.DEPARTMENT_NAME,
    D_E.CANT_EMPLEADOS
FROM
  (SELECT 
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    COUNT(*) AS CANT_EMPLEADOS
  FROM 
    DEPARTMENTS D
      INNER JOIN EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  GROUP BY
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME) D_E
WHERE 
  D_E.CANT_EMPLEADOS =
(SELECT 
  MIN(D_E.CANT_EMPLEADOS)
FROM
  (SELECT 
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    COUNT(*) AS CANT_EMPLEADOS
  FROM 
    DEPARTMENTS D
      INNER JOIN EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  GROUP BY
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    COUNT(*)) D_E)) 
    UNION
  (--DEPARTAMENTO CON MAYOR CANTIDAD
SELECT 
  D_E.DEPARTMENT_ID,
    D_E.DEPARTMENT_NAME,
    D_E.CANT_EMPLEADOS
FROM
  (SELECT 
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    COUNT(*) AS CANT_EMPLEADOS
  FROM 
    DEPARTMENTS D
      INNER JOIN EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  GROUP BY
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME) D_E
WHERE 
  D_E.CANT_EMPLEADOS =
(SELECT 
  MAX(D_E.CANT_EMPLEADOS)
FROM
  (SELECT 
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    COUNT(*) AS CANT_EMPLEADOS
  FROM 
    DEPARTMENTS D
      INNER JOIN EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  GROUP BY
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    COUNT(*)) D_E));

--TOTAL DE SUELDO MAS ALTO
SELECT
  MAX(TOTAL_SUELDOS) AS MAXIMO
FROM
  (SELECT
  J.EMPLOYEE_ID,
  J.FIRST_NAME,
  J.LAST_NAME,
  J.SALARY,
  COUNT (*) + 1 AS SUBORDINADOS,
  SUM(E.SALARY) + J.SALARY AS TOTAL_SUELDOS 
FROM
  EMPLOYEES E INNER JOIN EMPLOYEES J
    ON E.MANAGER_ID = J.EMPLOYEE_ID
GROUP BY
  J.EMPLOYEE_ID,
  J.FIRST_NAME,
  J.LAST_NAME,
  J.SALARY);
  
--PLANILLA MAS ALTA
SELECT
  J.EMPLOYEE_ID,
  J.FIRST_NAME,
  J.LAST_NAME,
  J.SALARY,
  COUNT (*) + 1 AS SUBORDINADOS,
  SUM(E.SALARY) + J.SALARY AS TOTAL_SUELDOS 
FROM
  EMPLOYEES E INNER JOIN EMPLOYEES J
    ON E.MANAGER_ID = J.EMPLOYEE_ID
GROUP BY
  J.EMPLOYEE_ID,
  J.FIRST_NAME,
  J.LAST_NAME,
  J.SALARY
HAVING SUM(E.SALARY) + J.SALARY = 
  (SELECT
  MAX(TOTAL_SUELDOS) AS MAXIMO
FROM
  (SELECT
  J.EMPLOYEE_ID,
  J.FIRST_NAME,
  J.LAST_NAME,
  J.SALARY,
  COUNT (*) + 1 AS SUBORDINADOS,
  SUM(E.SALARY) + J.SALARY AS TOTAL_SUELDOS 
FROM
  EMPLOYEES E INNER JOIN EMPLOYEES J
    ON E.MANAGER_ID = J.EMPLOYEE_ID
GROUP BY
  J.EMPLOYEE_ID,
  J.FIRST_NAME,
  J.LAST_NAME,
  J.SALARY));