--RETORNA EL LOS EMPLEADOS Y SU POSICION DE TRABAJO
SELECT
  E.EMPLOYEE_ID,
  E.FIRST_NAME,
  E.LAST_NAME,
  J.JOB_ID,
  J.JOB_TITLE
FROM
  EMPLOYEES E INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID;
    
--EMPLEADOS CONTRATADOS EL MISMO ANIO QUE SU JEFE
SELECT
  E.EMPLOYEE_ID,
  E.FIRST_NAME,
  E.LAST_NAME,
  E.HIRE_DATE,
  J.EMPLOYEE_ID,
  J.FIRST_NAME,
  J.LAST_NAME,
  J.HIRE_DATE
FROM
  EMPLOYEES E INNER JOIN EMPLOYEES J
    ON TO_CHAR(E.HIRE_DATE,'YYYY') =TO_CHAR(J.HIRE_DATE,'YYYY');
    
--EMPLEADOS QUE TRABAJAN EN LA CIUDAD DE SEATLE
SELECT
  E.EMPLOYEE_ID,
  E.FIRST_NAME,
  E.LAST_NAME,
  E.SALARY,
  E.HIRE_DATE,
  L.CITY,
  L.STATE_PROVINCE
FROM
  EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    INNER JOIN LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
WHERE
  L.CITY = 'Seattle';

--JEFE CON PLANILLA MAS ALTA
SELECT
  J.EMPLOYEE_ID,
  J.FIRST_NAME,
  J.LAST_NAME,
  SUMA(E.SALARY + J.SALARY) AS TOTAL_SU,
  count(*) AS N_SUBORD
FROM
  EMPLOYEES E INNER JOIN EMPLOYEES J
  ON E.MANAGER_ID = J.EMPLOYEE_ID
GROUP BY
  J.EMPLOYEE_ID,
  J.FIRST_NAME,
  J.LAST_NAME,
  TOTAL_SU,
  SUMA(E.SALARY);
  
--DEPARTAMENTO DE MENOR Y MAYOR DE EMPLEADOS
--SELECT
  --D.

