--UDF
-- en oracle existe una tabla que se llama: Dual

SELECT EMPLOYEE_ID, FIRST_NAME, TO_CHAR(HIRE_DATE,'MON-YYYY') AS MES_CONTRATO
FROM  DB.EMPLOYEES;

--DEVOLVER -1 PARA EL EMPLEADO QUE NO TIENE JEFE
SELECT EMPLOYEE_ID, FIRST_NAME, NVL(MANAGER_ID, -1) AS ID_JEFE
FROM  DB.EMPLOYEES;

--DEVOLVER EL MISMO EMPLEADO COMO JEFE PARA EL EMPLEADO QUE NO TIENE JEFE
SELECT EMPLOYEE_ID, FIRST_NAME, NVL(MANAGER_ID, EMPLOYEE_ID) AS ID_JEFE
FROM  DB.EMPLOYEES;

--Funcion(Q,b)
--	retorna Q+b
CREATE OR REPLACE FUNCTION FM_SUMA --RETORNA NULL
(
  PARAM1 IN NUMBER 
, PARAM2 IN NUMBER 
) RETURN NUMBER AS 
BEGIN
  RETURN PARAM1 + PARAM2;
END FM_SUMA;

CREATE OR REPLACE FUNCTION FM_SUMA --NO RETORNA NULL
(
  PARAM1 IN NUMBER 
, PARAM2 IN NUMBER 
) RETURN NUMBER AS 
BEGIN
  RETURN NVL(PARAM1,0) + NVL(PARAM2,0); -- <<-- USANDOLA
END FM_SUMA;

--PARA LLAMAR LA FUNCION
SELECT DB.FM_SUMA (NULL, 100) FROM DUAL; 

--FUNCION QUE RETORNA EL SUELDO MAXIMO DE UN COUNTRY QUE RECIBE DE PARAMETRO
CREATE OR REPLACE FUNCTION FM_GET_MAX_SUELDO 
(
  PCOUNTRY_ID IN VARCHAR2 
) RETURN NUMBER AS 
  nMax NUMBER;
BEGIN
  SELECT
    MAX(E.SALARY) AS MAX_SALDO
  INTO
    nMax
  FROM
    EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
      INNER JOIN LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
        INNER JOIN COUNTRIES C ON C.COUNTRY_ID = L.COUNTRY_ID
  WHERE
    C.COUNTRY_ID = PCOUNTRY_ID;
    RETURN nMax;
END FM_GET_MAX_SUELDO;

--PROBANDO FUNCION QUE RETORNA EL SUELDO MAXIMO DE UN COUNTRY

SELECT FM_GET_MAX_SUELDO('US') AS SUELDO_MAX FROM DUAL;

--EMPLEADO CON SALDO MAS ALTO DE ESTADOS UNIDOS
SELECT
  E.EMPLOYEE_ID,
  E.FIRST_NAME,
  E.LAST_NAME,
  E.SALARY,
  E.HIRE_DATE
FROM
  EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    INNER JOIN LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
      INNER JOIN COUNTRIES C ON C.COUNTRY_ID = L.COUNTRY_ID
WHERE
  C.COUNTRY_ID = 'US'
  AND
    E.SALARY = FM_GET_MAX_SUELDO('US'); -- <<-- USANDOLA

--RETORNA LOS COUNTRIES Y SU MAYOR SUELDO
SELECT COUNTRY_ID, FM_GET_MAX_SUELDO(COUNTRY_ID) AS MAX_SUELDO FROM COUNTRIES ;

--EMPLEADO QUE GANA MAS POR COUNTRY - RETORNA SOLO LOS COUNTRIES QUE TIENEN EMPLEADOS
SELECT
  E.EMPLOYEE_ID,
  E.FIRST_NAME,
  E.LAST_NAME,
  E.SALARY,
  E.HIRE_DATE,
  C.COUNTRY_ID
FROM
  EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    INNER JOIN LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID
      INNER JOIN COUNTRIES C ON C.COUNTRY_ID = L.COUNTRY_ID
WHERE
  E.SALARY = FM_GET_MAX_SUELDO(C.COUNTRY_ID);