SELECT 
  TO_CHAR(FECHA,'YYYY') AS ANIO,
  SUM(CASE WHEN TO_CHAR(FECHA,'MM') = '01' THEN TOTAL ELSE NULL END) AS ENE,
  SUM(CASE WHEN TO_CHAR(FECHA,'MM') = '02' THEN TOTAL ELSE NULL END) AS FEB,
  SUM(CASE WHEN TO_CHAR(FECHA,'MM') = '03' THEN TOTAL ELSE NULL END) AS MAR,
  SUM(CASE WHEN TO_CHAR(FECHA,'MM') = '04' THEN TOTAL ELSE NULL END) AS ABR,
  SUM(CASE WHEN TO_CHAR(FECHA,'MM') = '05' THEN TOTAL ELSE NULL END) AS MAY,
  SUM(CASE WHEN TO_CHAR(FECHA,'MM') = '06' THEN TOTAL ELSE NULL END) AS JUN,
  SUM(CASE WHEN TO_CHAR(FECHA,'MM') = '07' THEN TOTAL ELSE NULL END) AS JUL,
  SUM(CASE WHEN TO_CHAR(FECHA,'MM') = '08' THEN TOTAL ELSE NULL END) AS AGO,
  SUM(CASE WHEN TO_CHAR(FECHA,'MM') = '09' THEN TOTAL ELSE NULL END) AS SEP,
  SUM(CASE WHEN TO_CHAR(FECHA,'MM') = '10' THEN TOTAL ELSE NULL END) AS OCT,
  SUM(CASE WHEN TO_CHAR(FECHA,'MM') = '11' THEN TOTAL ELSE NULL END) AS NOV,
  SUM(CASE WHEN TO_CHAR(FECHA,'MM') = '12' THEN TOTAL ELSE NULL END) AS DIC
FROM 
  VENTAS
GROUP BY 
  TO_CHAR(FECHA,'YYYY');
  
SELECT
  CLIENTE,
  SUM(TOTAL) AS TOTAL_2
FROM
  VENTAS
WHERE
  TO_CHAR(FECHA,'YYYY') = '2014'
GROUP BY
  CLIENTE
ORDER BY
  TOTAL_2 DESC;
--CLIENTE 2,3,4  

SELECT
  TO_CHAR(FECHA,'YYYY') AS ANIO,
  SUM(CASE WHEN CLIENTE = 'Cliente 4' THEN TOTAL ELSE NULL END) AS CLIENTE_4,
  SUM(CASE WHEN CLIENTE = 'Cliente 3' THEN TOTAL ELSE NULL END) AS CLIENTE_3,
  SUM(CASE WHEN CLIENTE = 'Cliente 2' THEN TOTAL ELSE NULL END) AS CLIENTE_2
FROM
  VENTAS
GROUP BY TO_CHAR(FECHA,'YYYY');